openapi: 3.1.0
info:
  version: 1.0.0
  title: MyMarkit SaaS V1
  termsOfService: https://mymarkitinc.com/terms/
  contact:
    email: contact@mymarkitinc.com
    url: http://mymarkitinc.com/contact
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://mymarkit-production.s3.amazonaws.com/img/logos/logo-header.svg
  description: "This is an **example** API to demonstrate features of the OpenAPI specification.\r\n\r\n# Introduction\r\n\r\nThis API implementation guide is intended to to be a good starting point for\r\nimplementing various MyMarkit SaaS products.\r\n\r\n[Company Site](https://mymarkit.com).\r\n"
tags:
  - name: Payment with MarkitPay (Fiat)
    description: Universal Payment Processor with MarkitPay (Fiat).
  - name: Payment with MarkitPay (Crypto)
    description: Universal Payment Processor with MarkitPay (Crypto).
  - name: Webhook confirmation from MarkitPay (Fiat)
    description: Webhook confirmation from Universal Payment Processor with MarkitPay (Fiat).
  - name: Webhook confirmation from MarkitPay (Crypto)
    description: Webhook confirmation from Universal Payment Processor with MarkitPay (Crypto).
  - name: Add a single entry record to MarkitChain
    description: Add a single entry record to MarkitChain.        
  - name: Retrieve a single entry record from MarkitChain
    description: Retrieve a single entry record from MarkitChain.       
  - name: Retrieve a collection of entry records from MarkitChain
    description: Retrieve a collection of entry records from MarkitChain.      
  - name: Deprecate a single entry record on MarkitChain
    description: Deprecate a single entry record on MarkitChain.      
servers:
  - url: https://8gu4au3nb4.execute-api.us-east-1.amazonaws.com/test
paths:
  /api/v1/payments/adyen:
    post:
      tags:
        - Payment with MarkitPay (Fiat)
      summary: Create a payment page with MarkitPay (Fiat)
      description: >-
        Create a universal payment page loaded with payment methods from MarkitPay (Fiat)
        dashboard
      operationId: UniversalAdyenPayment
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              $ref: '#/components/headers/ExpiresAfter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentAdyenResponse'
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentAdyen'
        description: Payment payload
        required: true
  /api/v1/payments/coinbase:
    post:
      tags:
        - Payment with MarkitPay (Crypto)
      summary: Create a payment page with MarkitPay (Crypto)
      description: >-
        Create a universal payment page loaded with payment methods from
        MarkitPay (Crypto) dashboard
      operationId: UniversalCoinbasePayment
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              $ref: '#/components/headers/ExpiresAfter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentCoinbaseResponse'
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentCoinbase'
        description: Payment payload
        required: true
  /user-provided-url-for-webhook-adyen:
    post:
      tags:
        - Webhook confirmation from MarkitPay (Fiat)
      summary: Create a webhook confirmation response from MarkitPay (Fiat) payment
      description: Create a webhook JSON confirmation response page from MarkitPay (Fiat) payment
      operationId: WebhookAdyenPayment
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              $ref: '#/components/headers/ExpiresAfter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookAdyenResponse'
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookAdyenRequest'
        description: webhook request body
        required: true
  /user-provided-url-for-webhook-coinbase:
    post:
      tags:
        - Webhook confirmation from MarkitPay (Crypto)
      summary: Create a webhook confirmation response from MarkitPay (Crypto) payment
      description: Create a webhook JSON confirmation response page from MarkitPay (Crypto) payment
      operationId: WebhookCoinbasePayment
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              $ref: '#/components/headers/ExpiresAfter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookCoinbaseResponse'
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookCoinbaseRequest'
        description: webhook request body
        required: true
  /api/v1/markitchain/post:
    post:
      tags:
        - Add a single entry record to MarkitChain
      summary: Create a Blockchain ledger entry in MarkitChain
      description: >-
        Create a Blockchain ledger entry in MarkitChain from customer request
      operationId: postEntry
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              $ref: '#/components/headers/ExpiresAfter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateMarkitChainResponse'
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMarkitChain'
        description: Create MarkitChain Request Body
        required: true        
  /api/v1/markitchain/entry:
    get:
      tags:
        - Retrieve a single entry record from MarkitChain
      summary: Retrieve an entry with MarkitChain
      description: >-
        Retrieve a single Blockchain ledger entry in MarkitChain based on ledger_id
      operationId: getEntry
      security:
        - ApiKeyAuth: []
      parameters:
        - name: ledger_id
          in: query
          description: ledger_id of the product to be searched for
          required: true
          schema:
            type: string        
      responses:
        '200':
          description: OK
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              $ref: '#/components/headers/ExpiresAfter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryMarkitChainResponse'
        '401':
          description: Unauthorized
    delete:
      tags:
        - Deprecate a single entry record on MarkitChain
      summary: Deprecate a single entry record on MarkitChain
      description: >-
        Deprecate a single entry record on the chain in MarkitChain based on ledger_id
      operationId: deleteEntry
      security:
        - ApiKeyAuth: []
      parameters:
        - name: ledger_id
          in: query
          description: ledger_id of the product to be deprecated
          required: true
          schema:
            type: string        
      responses:
        '200':
          description: OK
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              $ref: '#/components/headers/ExpiresAfter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryDeprecateMarkitChainResponse'
        '401':
          description: Unauthorized              
  /api/v1/markitchain/entries:
    get:
      tags:
        - Retrieve a collection of entry records from MarkitChain
      summary: Retrieve a collection of entry records from MarkitChain
      description: >-
        Retrieve a collection of Blockchain ledger entries in MarkitChain based on a collection of ledger_is
      operationId: getEntries
      security:
        - ApiKeyAuth: []
      parameters:
        - name: ledger_ids
          in: query
          description: an array of ledger_ids to be searched for
          required: true
          schema:
            type: string        
      responses:
        '200':
          description: OK
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              $ref: '#/components/headers/ExpiresAfter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntriesMarkitChainResponse'
        '401':
          description: Unauthorized                    

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    PaymentAdyen:
      type: object
      properties:
        merchantId:
          description: unique merchant id
          type: string
          minLength: 4
          example: WonderWebShop1
        value:
          description: total amount to pay
          type: string
          minLength: 1
          example: '100.15'
        currency:
          description: currency
          type: string
          minLength: 1
          example: EUR
        returnURL:
          description: the url to return to upon successful payment completion
          type: string
          minLength: 1
          example: https://saasdevs.net
    PaymentAdyenResponse:
      type: object
      properties:
        transactionId:
          description: unique transaction Id
          type: string
          minLength: 4
          example: JUWX2123
        paymentPageUrl:
          description: payment page url
          type: string
          minLength: 1
          example: https://saasdevs.net/payments/adyen?transactionId=JUWX2123
        createStatus:
          description: status of the page creation
          type: string
          minLength: 1
          example: true
    PaymentCoinbase:
      type: object
      properties:
        merchantId:
          description: unique merchant id
          type: string
          minLength: 4
          example: WonderWebShop1
        value:
          description: total amount to pay
          type: string
          minLength: 1
          example: '100.15'
        currency:
          description: currency
          type: string
          minLength: 1
          example: USD
        returnURL:
          description: the url to return to upon successful payment completion
          type: string
          minLength: 1
          example: https://saasdevs.net
    CreateMarkitChain:
      type: object
      properties:
        ledger_id:
          description: ledger_id of the product customer wants to create
          type: integer
          minLength: 1
          example: 12345     
        field_data:   
          description: field data which can go up to 30 fields, subject to change
          type: array
          items: 
            type: object
            minLength: 1
            properties:
              name:
                description: name
                type: string
                minLength: 1
              value:
                description: value
                type: string
                minLength: 1
          example:   
            - name: item_name
              value: LV Handbag
            - name: color
              value: blue                                      
                
    PaymentCoinbaseResponse:
      type: object
      properties:
        transactionId:
          description: unique transaction Id
          type: string
          minLength: 4
          example: JUWX2123
        paymentPageUrl:
          description: payment page url
          type: string
          minLength: 1
          example: https://saasdevs.net/payments/coinbase?transactionId=JUWX2123
        createStatus:
          description: status of the page creation
          type: string
          minLength: 1
          example: true
    CreateMarkitChainResponse:
      type: object
      properties:
        ledger_id:
          description: unique ledger_id for the customer create request
          type: integer
          minLength: 1
          example: 12345
        field_data:   
          description: field data
          type: array
          items: 
            type: object
            minLength: 1
            properties:
              name:
                description: name
                type: string
                minLength: 1
              value:
                description: value
                type: string
                minLength: 1
          example:   
            - name: item_name
              value: LV Handbag
            - name: color
              value: blue      
    EntryMarkitChainResponse:
      type: object
      properties:
        ledger_id:
          description: ledger_id from customer's search request
          type: integer
          minLength: 1
          example: 12345
        field_data:   
          description: field data
          type: array
          items: 
            type: object
            minLength: 1
            properties:
              name:
                description: name
                type: string
                minLength: 1
              value:
                description: value
                type: string
                minLength: 1
          example:   
            - name: item_name
              value: LV Handbag
            - name: color
              value: blue                  
    EntriesMarkitChainResponse:
      type: array
      description: query result entries
      items:
        type: object
        minLength: 1        
        properties:
          ledger_id:
            description: ledger_id's from customer's search request
            type: integer
            minLength: 1
            example: 12345
          field_data:   
            description: field data
            type: array
            items: 
              type: object
              minLength: 1
              properties:
                name:
                  description: name
                  type: string
                  minLength: 1
                value:
                  description: value
                  type: string
                  minLength: 1
            example:   
              - name: item_name
                value: LV Handbag
              - name: color
                value: blue                  
    EntryDeprecateMarkitChainResponse:
      type: object
      properties:
        ledger_id:
          description: ledger_id removed per customer's deprecate request
          type: integer
          minLength: 1
          example: 12345

    WebhookAdyenRequest:
      type: object
      properties:
        upp-api-key:
          description: unique upp api key
          type: string
          minLength: 4
          example: 12345678xyz
        upp-client-key:
          description: unique client key per customer
          type: string
          minLength: 4
          example: xyzw12345
    WebhookAdyenResponse:
      type: object
      properties:
        live:
          description: live
          type: string
          minLength: 4
          example: 'false'
        notificationItems:
          description: notification items
          type: array
          items:
            type: object
            minLength: 1
            example:
              amount:
                currency: EUR
                value: 1000
              eventCode: AUTHORISATION
              eventDate: '2022-06-20T03:26:47+02:00'
              merchantAccountCode: MyMarkit_US
              merchantReference: Reference 46b0ad7e-fa3b-466e-823e-b04e6bbba1d4
              operations:
                - REFUND
              paymentMethod: ideal
              pspReference: QW2KB9G5F4BLNK82
              reason: ''
              success: 'true'
    WebhookCoinbaseRequest:
      type: object
      properties:
        upp-api-key:
          description: unique upp api key
          type: string
          minLength: 4
          example: 12345678xyz
        upp-client-key:
          description: unique client key per customer
          type: string
          minLength: 4
          example: xyzw12345
    WebhookCoinbaseResponse:
      type: object
      properties:
        attempt_number:
          description: attempt number
          type: integer
          minLength: 1
          example: 1
        id:
          description: id
          type: string
          minLength: 1
          example: 51dc060b-8ac3-4615-9ef1-b4e3206cdee0
        scheduled_for:
          description: scheduled for
          type: string
          minLength: 1
          example: '2022-07-01T22:10:50Z'
        event:
          description: event
          type: object
          minLength: 1
          example:
            api_version: '2018-03-22'
            created_at: '2022-07-01T22:10:50Z'
            data:
              id: 937d2722-eac6-4e43-87ee-36320b911ad7
              code: 8HWHNCW4
              name: UPP Portal
              utxo: false
              pricing:
                dai:
                  amount: '10.432267416236208673'
                  currency: DAI
                usdc:
                  amount: '10.428616'
                  currency: USDC
                local:
                  amount: '10.00'
                  currency: EUR
                tether:
                  amount: '10.441616'
                  currency: USDT
                bitcoin:
                  amount: '0.00053858'
                  currency: BTC
                dogecoin:
                  amount: '158.46552382'
                  currency: DOGE
                ethereum:
                  amount: '0.009800000'
                  currency: ETH
                litecoin:
                  amount: '0.20400266'
                  currency: LTC
                shibainu:
                  amount: '1043905.517781834434434434'
                  currency: SHIB
                bitcoincash:
                  amount: '0.10269945'
                  currency: BCH
              fee_rate: 0.01
              logo_url: >-
                https://res.cloudinary.com/commerce/image/upload/v1655522635/nzlih20yojcvbicpl3e1.png
              metadata: {}
              payments: []
              resource: charge
              timeline:
                - time: '2022-07-01T22:10:50Z'
                  status: NEW
              addresses:
                dai: '0xd2eabd78481ea6b349d3a701847e08ba24fb7d44'
                usdc: '0xd2eabd78481ea6b349d3a701847e08ba24fb7d44'
                tether: '0xd2eabd78481ea6b349d3a701847e08ba24fb7d44'
                bitcoin: 3GwfdMbWDZYC5p9Jf93u6L3zJvExgarFHp
                dogecoin: DEvZDwdvhSyU5CHB9ZFXFosyrhfkcXukWE
                ethereum: '0xd2eabd78481ea6b349d3a701847e08ba24fb7d44'
                litecoin: MBCMuEGiH7Nej2sz9CHTzTWsDuSxCc9bth
                shibainu: '0xd2eabd78481ea6b349d3a701847e08ba24fb7d44'
                bitcoincash: qppy6ftf8lszm06q6jyx3pyqmcdv4cdgtgt2cenl3c
              pwcb_only: false
              cancel_url: https://saasdevs.net/coinbase/cancel/
              created_at: '2022-07-01T22:10:50Z'
              expires_at: '2022-07-01T23:10:50Z'
              hosted_url: https://commerce.coinbase.com/charges/8HWHNCW4
              brand_color: '#E3B14D'
              description: 'Total Charge in Local Currency:'
              fees_settled: true
              pricing_type: fixed_price
              redirect_url: https://saasdevs.net/coinbase/success/
              support_email: tim@mymarkit.com
              brand_logo_url: >-
                https://res.cloudinary.com/commerce/image/upload/v1655522635/nzlih20yojcvbicpl3e1.png
              exchange_rates:
                BCH-USD: '101.545'
                BTC-USD: '19363.13'
                DAI-USD: '0.99965'
                ETH-USD: '1064.11'
                LTC-USD: '51.12'
                DOGE-USD: '0.06581'
                SHIB-USD: '0.00000999'
                USDC-USD: '1.0'
                USDT-USD: '0.998755'
              offchain_eligible: false
              organization_name: MyMarkit!
              payment_threshold:
                overpayment_absolute_threshold:
                  amount: '0.10'
                  currency: USD
                overpayment_relative_threshold: '0.01'
                underpayment_absolute_threshold:
                  amount: '0.10'
                  currency: USD
                underpayment_relative_threshold: '0.01'
              local_exchange_rates:
                BCH-EUR: '97.37'
                BTC-EUR: '18567.31'
                DAI-EUR: '0.96'
                ETH-EUR: '1020.38'
                LTC-EUR: '49.02'
                DOGE-EUR: '0.06'
                SHIB-EUR: '0.00'
                USDC-EUR: '0.96'
                USDT-EUR: '0.96'
            id: b180df29-0c27-44e1-9129-3d8cab79ce18
            resource: event
            type: charge:created
  headers:
    ExpiresAfter:
      description: date in UTC when token expires
      schema:
        type: string
        format: date-time
